
POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "title": "lista noturna",
    "author" : "jose",
    "description" : "lista de tarefas noturnas",
    "tasks": [
        {
            "title": "Estudar html",
        },
        {
            "title": "Estudar js",
        }
    ]
}

### 

POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "title": "lista diurna",
    "author" : "jose",
    "description" : "lista de tarefas noturnas",
    "tasks": [
        {
            "title": "Estudar python",
        }    
    ]
}

###
GET http://localhost:3000/api/lists

###

POST http://localhost:3000/api/lists/670ea7e6e28e089c7e23c503/addTask
Content-Type: application/json

{
    "title": "Estudar python",
    "completed": false
}

###

POST http://localhost:3000/api/lists/670ea7e6e28e089c7e23c503/removeTask
Content-Type: application/json

{
    "taskTitle": "Estudar node"
}

###

POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "title": "lista noturna",
    "description" : "lista de tarefas noturnas"
}





